# Generated by Django 4.0.2 on 2022-02-07 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.TextField(default='no gene')),
                ('sequence', models.TextField(default='no sequence')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutation', models.TextField(default='no mutation')),
                ('hphob_hphil', models.TextField(default='no mutation')),
                ('protonate', models.TextField(default='no mutation')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutation', to='gene.gene')),
            ],
        ),
        migrations.AddField(
            model_name='gene',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene', to='gene.user'),
        ),
    ]
