# Generated by Django 4.0.2 on 2022-02-08 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gene', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='user',
        ),
    ]
