# Generated by Django 4.0.2 on 2022-02-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene', '0002_remove_gene_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gene',
            old_name='sequence',
            new_name='sequence_one',
        ),
        migrations.AddField(
            model_name='gene',
            name='sequence_two',
            field=models.TextField(default='no sequence'),
        ),
    ]
